### ISSUE TITLE
Conversion to int - is it really needed?

### ISSUE THREAD

**Issue by blele** [SachinBhosale13/logParser#4]
https://github.com/SachinBhosale13/logParser/blob/7746135417a86c1520eaeffa8c103f5324852219/logParser/Program.cs#L68

**Comment by SachinBhosale13** [comment]
Actually there is no need. but initially I considered whatever inside the console.writeline is string and I wanted to do i+1. So I first thought it will be better to convert it first. But there was no need. Fixed this. thank you.
